### ISSUE TITLE
Command can't be register because of PluginCommand

### ISSUE THREAD

**Issue by noaottermann** [Sunderia/SunderiaUtils#1]
java.lang.ClassCastException: class net.sunderia.skyblock.commands.TestCommand cannot be cast to class org.bukkit.command.PluginCommand (net.sunderia.skyblock.commands.TestCommand is in unnamed module of loader 'SunderiaSkyblock-1.0-SNAPSHOT-all.jar' @45b09ea0; org.bukkit.command.PluginCommand is in unnamed module of loader java.net.URLClassLoader @504bae78)
    at fr.sunderia.sunderiautils.SunderiaUtils.lambda$registerCommands$1(SunderiaUtils.java:65) ~[SunderiaSkyblock-1.0-SNAPSHOT-all.jar:?]
    at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
    at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
    at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
    at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992) ~[?:?]
    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
    at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
    at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
    at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
    at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
    at fr.sunderia.sunderiautils.SunderiaUtils.registerCommands(SunderiaUtils.java:63) ~[SunderiaSkyblock-1.0-SNAPSHOT-all.jar:?]
    at net.sunderia.skyblock.SunderiaSkyblock.onEnable(SunderiaSkyblock.java:33) ~[SunderiaSkyblock-1.0-SNAPSHOT-all.jar:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
    at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:562) ~[paper-1.18.1.jar:git-Paper-215]
    at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:476) ~[paper-1.18.1.jar:git-Paper-215]
    at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:736) ~[paper-1.18.1.jar:git-Paper-215]
    at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:503) ~[paper-1.18.1.jar:git-Paper-215]
    at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:313) ~[paper-1.18.1.jar:git-Paper-215]
    at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1211) ~[paper-1.18.1.jar:git-Paper-215]
    at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-215]
    at java.lang.Thread.run(Thread.java:833) ~[?:?]
    

```java
package net.sunderia.skyblock.commands;

import fr.sunderia.sunderiautils.commands.CommandInfo;
import fr.sunderia.sunderiautils.commands.PluginCommand;
import org.bukkit.entity.Player;
import org.bukkit.plugin.java.JavaPlugin;
import org.jetbrains.annotations.NotNull;

@CommandInfo(name = "test", aliases = {"t"}, permission = "sunderiaskyblock.test", requiresPlayer = true)
public class TestCommand extends PluginCommand {

    /**
     * This constructor is used to register the command and check if the command has the correct annotation.
     *
     * @param plugin An instance of the plugin.
     */
    public TestCommand(JavaPlugin plugin) {
        super(plugin);
    }

    @Override
    public void onCommand(@NotNull Player player, @NotNull String[] args) {

    }

}
```

**Comment by noaottermann** [comment]
this is error when I run spigot

**Comment by Minemobs** [comment]
Can you post your code please ?

**Comment by Minemobs** [comment]
fixed

**Comment by noaottermann** [comment]
no

**Comment by noaottermann** [comment]
Error occurred while enabling SunderiaSkyblock v1.18.1 (Is it up to date?)
java.lang.RuntimeException: java.lang.IllegalStateException: Plugin is null and it can't be found because I'm lazy to write a good method to find it.
	at fr.sunderia.sunderiautils.SunderiaUtils.getPlugin(SunderiaUtils.java:172) ~[SunderiaSkyblock-1.0-SNAPSHOT-all.jar:?]
	at fr.sunderia.sunderiautils.utils.ItemBuilder.build(ItemBuilder.java:260) ~[SunderiaSkyblock-1.0-SNAPSHOT-all.jar:?]
	at net.sunderia.skyblock.SunderiaSkyblock.onEnable(SunderiaSkyblock.java:38) ~[SunderiaSkyblock-1.0-SNAPSHOT-all.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:562) ~[paper-1.18.1.jar:git-Paper-215]
	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:476) ~[paper-1.18.1.jar:git-Paper-215]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:736) ~[paper-1.18.1.jar:git-Paper-215]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:503) ~[paper-1.18.1.jar:git-Paper-215]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:313) ~[paper-1.18.1.jar:git-Paper-215]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1211) ~[paper-1.18.1.jar:git-Paper-215]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-215]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalStateException: Plugin is null and it can't be found because I'm lazy to write a good method to find it.
	at fr.sunderia.sunderiautils.SunderiaUtils.lambda$getPlugin$7(SunderiaUtils.java:169) ~[SunderiaSkyblock-1.0-SNAPSHOT-all.jar:?]
	at java.util.Optional.ifPresentOrElse(Optional.java:198) ~[?:?]
	at fr.sunderia.sunderiautils.SunderiaUtils.getPlugin(SunderiaUtils.java:168) ~[SunderiaSkyblock-1.0-SNAPSHOT-all.jar:?]
	... 13 more

**Comment by Minemobs** [comment]
You need to add `SunderiaUtils.of(this)` in the `onEnable` method

**Comment by noaottermann** [comment]
Already writen

**Comment by noaottermann** [comment]
```java
package net.sunderia.skyblock;

import fr.sunderia.sunderiautils.SunderiaUtils;
import fr.sunderia.sunderiautils.utils.ItemBuilder;
import net.sunderia.skyblock.listener.Events;
import net.sunderia.skyblock.objects.CustomEquipment;
import org.bukkit.Bukkit;
import org.bukkit.ChatColor;
import org.bukkit.Material;
import org.bukkit.NamespacedKey;
import org.bukkit.plugin.java.JavaPlugin;

import java.io.IOException;
import java.util.Arrays;
import java.util.Locale;

public class SunderiaSkyblock extends JavaPlugin {

    private static SunderiaSkyblock instance;
    public static final String header = ChatColor.DARK_GREEN + "[" + ChatColor.GREEN + "SunderiaSkyblock" + ChatColor.DARK_GREEN + "] ";

    @Override
    public void onLoad() {
        instance = this;
    }

    @Override
    public void onEnable() {
        SunderiaUtils.of(this);
        this.saveDefaultConfig();
        try {
            SunderiaUtils.registerListeners("net.sunderia.skyblock.listener");
            SunderiaUtils.registerCommands("net.sunderia.skyblock.commands");
        } catch (IOException e) {
            e.printStackTrace();
        }
        Bukkit.getScheduler().runTaskTimer(this, Events::onTickEvent, 20, 20);
        CustomEquipment e = new CustomEquipment(new ItemBuilder(Material.NETHERITE_BLOCK).build(), new ItemBuilder(Material.NETHERITE_INGOT).build(), true);
        e.initArmor();
        e.initTools();
        getLogger().info("[SunderiaSkyblock] Plugin is enabled.");
    }

    @Override
    public void onDisable() {
        getLogger().info("[SunderiaSkyblock] Plugin is disabled.");
    }

    public static NamespacedKey getKey(String key) {
        return new NamespacedKey(getInstance(), key);
    }

    public static String arrayToString(String[] array){
        return Arrays.toString(array).replace("[", "").replace("]", "").replace(", ", "");
    }

    public static String stringToKey(String string){
        return string.strip().toLowerCase(Locale.ROOT);
    }

    public static SunderiaSkyblock getInstance(){
        return instance;
    }

}
```

**Comment by Minemobs** [comment]
Finally fixed
